<?php
include('Point.php');
class MovablePoint extends Point{
    protected $xSpeed = 0.0;
    protected $ySpeed = 0.0;

    public function setMovablePoint($x,$y,$xSpeed,$ySpeed){
        $this->x = $x;
        $this->y = $y;
        $this->xSpeed =$xSpeed;
        $this->ySpeed =$ySpeed;

    }
    public function getMovablePoint(){
        return $this->x ." ".$this->y ." ".$this->xSpeed ." " . $this->ySpeed;
    }

    /**
     * @return float
     */
    public function getXSpeed()
    {
        return $this->xSpeed;
    }

    /**
     * @param float $xSpeed
     */
    public function setXSpeed($xSpeed)
    {
        $this->xSpeed = $xSpeed;
    }

    /**
     * @return float
     */
    public function getYSpeed()
    {
        return $this->ySpeed;
    }

    /**
     * @param float $ySpeed
     */
    public function setYSpeed($ySpeed)
    {
        $this->ySpeed = $ySpeed;
    }
    public function setSpeed ($xSpeed,$ySpeed){
        $this->xSpeed =$xSpeed;
        $this->ySpeed =$ySpeed;
        $this->array[0]=$xSpeed;
        $this->array[1] = $ySpeed;

    }
    public function getSpeed (){
        return $this->array;
    }
    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }
    public function move(){
        $this->x += $this->xSpeed;
        $this->y +=$this->ySpeed;
        return $this;
    }
}
